---
- hosts: localhost
  vars:
    variable: 'value of variable'
  tasks:
  - name: test
    block:
    - debug: msg={{variable | checksum}}
    - debug: msg={{othervariable | default('Default value')}}
  - name: Attempt and graceful roll back demo
    block:
    - debug:
        msg: 'I execute normally'
    - command: /bin/false
    - debug:
        msg: 'I never execute, due to the above task failing'
    rescue:
    - debug:
        msg: 'I caught an error'
    - command: /bin/false
    - debug:
        msg: 'I also never execute :-('
    always:
    - debug:
        msg: "This always executes"