---
- hosts: localhost
  tasks:
  - name: Create private/public keys
    shell: ssh-keygen -b 2048 -t rsa -f /home/vagrant/.ssh/id_rsa -q -N ""
    args:
      creates: /home/vagrant/.ssh/id_rsa
- hosts: nodes
  tasks:
  - name: Copy public ssh key to remote nodes
    authorized_key:
      user: vagrant
      key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
      state: present
    notify:
    - Show message
  handlers:
  - name: Show message
    debug: msg="Done"