---
- hosts: localhost
  vars_files:
  - vars.yaml
  vars:
    SECRET1: secret data from variable
  tasks:
    - name: Show message
      debug: msg="Message with `{{ SECRET1 }}` and `{{ SECRET2 }}` 🔥"
